apiVersion: v1
kind: Service
metadata:
  name: rollouts-demo-service-blue
spec:
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
    nodePort: 33500
  selector:
    app: example
  type: NodePort
